node {
    stage('Checkout - Authservice') {
        git branch: 'main', url: 'https://github.com/Lunatunny/MicroAuth.git'
    }
    
    stage('Gradle Build - Authservice') {
        sh 'gradle -b MicroAuth/build.gradle build -x test'
    }
    
    stage ('Gradle Bootjar - Package - Authservice'){
        sh 'gradle -b MicroAuth/build.gradle bootjar'
    }
    
    stage ('User Acceptance Test - Authservice'){
    	def response = input message: 'Is this build good for release?',
    	parameters: [choice(choices: 'Yes\nNo',
    	description: '', name: 'Pass')]
    	
    	if(response=='Yes') {
    		stage('Release - Authservice') {
    			sh 'gradle -b MicroAuth/build.gradle build'
    		}
    	}
    }
}